Allow nonzero landing height in PositionHlCommander
bitcraze/crazyflie-lib-python pull request #242
Opened 2021-06-03 00:25 UTC by CoolBots

We have encountered a need to land on objects (landing pads) that are situated at a different height than the takeoff (or, more specifically, calibration) height. The function `land()` in `crazyflie.HighLevelCommander` class accepts an `absolute_height_m` parameter, which is hard-coded to zero in `positioning.PositionHlCommander` class's version of this function (which is a pass-through function to the former one). This PR adds an optional parameter to the latter function, as well as introduces a method of specifying a `default_landing_height` at either initialization (`__init__` function), with default of 0.0, or as a separate function call to a newly introduced `set_landing_height` function. A very simple usage example was also added to `position_commander_demo.py` 

We find this functionality a useful addition, with no breaking changes to existing code. 

Unit test `test_that_it_goes_down_to_set_landing_height_on_landing` added; physically tested on Crazyflie 2.1 with Lighthouse deck.

2021-06-03 08:47 UTC, krichardsson commented
Nice extension of the class, good idea!

I will review the code add some comments in the code.

There also seems to be some minor styling problems that break the build, the static code analyses tools we use are very (too?) picky. You can see the log here https://github.com/bitcraze/crazyflie-lib-python/runs/2735315626?check_suite_focus=false#step:3:100

Thanks!

2021-06-03 08:55 UTC, krichardsson requested changes

2021-06-03 08:55 UTC, krichardsson commented on cflib/positioning/position_hl_commander.py
> +    def land(self, velocity=DEFAULT, landing_height=0.0):
I think the user would expect a call to `land()` to use the `default_landing_height` that was set when the class was instantiated, the current implementation would try to land at 0.0. To get the desired functionality you will have to follow the same pattern that is used for the `velocity` parameter and set it to `DEFAULT`.

2021-06-03 08:55 UTC, krichardsson commented on cflib/positioning/position_hl_commander.py
> +        self.land(landing_height=self._default_landing_height)
With the proposed change to the `land()` method, `__exit__()` should only call `land()` without any arguments

2021-06-04 09:50 UTC, CoolBots commented
@krichardsson Very good point; I corrected my code and the affected unit test. I also fixed up the styling. Thanks!

2021-06-09 05:33 UTC, merged

2021-06-09 05:34 UTC, krichardsson commented
Merged.
Thanks!