Add possibility of using Wireshark in CRTP debugging
bitcraze/crazyflie-lib-python pull request #282
Opened 2021-11-18 19:54 UTC by jonasdn

# cflib: Add PCAP log

After this you can specify:

```
$ CRTP_PCAP_LOG=filename.pcap python3 examples/swarm/hl-commander-swarm.py
```

To generate a PCAP file with the CRTP communication seen by crazyradio.

The PCAP record generated is structured as:

| receive | address | channel | radio devid | crtp header | crtp data |
| 1 byte   | 5 bytes  |  1 byte   |    1 byte      |    1 byte      |   n bytes |

Where the receive bye indicates whether this is an incoming packet or
not.

# Add Wireshark dissector

![fancy](https://user-images.githubusercontent.com/974401/142487116-02abf4ff-143f-4c57-9793-28a68b8e78c5.png)

```bash
$ tshark -r test.pcap "crtp.port == 8"
    6   0.003333 00:DE:AD:BE:EF (10) → Radio #0     CRTP 13 Setpoint Highlevel
13158   5.176752     Radio #0 → 00:DE:AD:BE:EF (10) CRTP 24 Setpoint Highlevel
13163   5.178626 00:DE:AD:BE:EF (10) → Radio #0     CRTP 13 Setpoint Highlevel
17768   8.179085     Radio #0 → 00:DE:AD:BE:EF (10) CRTP 32 Setpoint Highlevel
17773   8.181294 00:DE:AD:BE:EF (10) → Radio #0     CRTP 13 Setpoint Highlevel
21223  10.181543     Radio #0 → 00:DE:AD:BE:EF (10) CRTP 32 Setpoint Highlevel
21228  10.183293 00:DE:AD:BE:EF (10) → Radio #0     CRTP 13 Setpoint Highlevel
24030  12.182588     Radio #0 → 00:DE:AD:BE:EF (10) CRTP 32 Setpoint Highlevel
24035  12.185723 00:DE:AD:BE:EF (10) → Radio #0     CRTP 13 Setpoint Highlevel
26449  14.184183     Radio #0 → 00:DE:AD:BE:EF (10) CRTP 32 Setpoint Highlevel
26454  14.185862 00:DE:AD:BE:EF (10) → Radio #0     CRTP 13 Setpoint Highlevel
28388  16.187258     Radio #0 → 00:DE:AD:BE:EF (10) CRTP 24 Setpoint Highlevel
28393  16.188963 00:DE:AD:BE:EF (10) → Radio #0     CRTP 13 Setpoint Highlevel
30533  18.190823     Radio #0 → 00:DE:AD:BE:EF (10) CRTP 11 Setpoint Highlevel
```

2021-11-22 05:56 UTC, jonasdn commented
So, @ataffanel you see I adder some general (non-CRTP) Crazyradio data to the PCAP. Like the source address and the devid of the radio and also a byte indicating if the packet was incoming or not. 

This is not well thought out, neither in regard to the right now nor in regard to a shiny new future. And we could probably do better and achieve the same. Any ideas?

Could we encode something more than the devid in a byte?

Like:

| Bit 0 - 4 | Bit 5 - 8 |
| ---------- | ----------- |
| usb/radio/ble/other| identifier |

Do we need a byte indicating incoming packet or can we infer it in someway?

2021-12-15 13:02 UTC, knmcguire commented on wireshark/README.md
> +# How to analyze CFLIB CRTP traffic using Wireshark
Shouldn't this be part of the CFlib doc folder? it would be good to have all documentation at on place.

2022-01-12 12:17 UTC, ataffanel commented
Looks great!

The dissector file should likely not be in the project root. I think the "tools" folder would feel better an less noisy.

The decoding is a bit "sparse" so far. This is something that can be improved later but it would be nice to add at least an "undecoded" field to show the user the rest of the packet, for example in that case to make clear that there is data in the packet:
![Screenshot from 2022-01-12 12-59-45](https://user-images.githubusercontent.com/6381499/149136479-0cc721b7-9b94-4d60-8ac3-9df4ab863022.png)

2022-01-12 13:00 UTC, ataffanel requested changes
See my comment.

2022-01-13 07:57 UTC, jonasdn commented
Thanks for comments! I pushed two commits addressing your issues!

2022-01-13 10:19 UTC, ataffanel approved these changes

2022-01-13 10:20 UTC, ataffanel commented
Looks great to me, great addition!

2022-01-13 10:58 UTC, merged