Improved HL commander - spiral & linear segment
bitcraze/crazyflie-lib-python pull request #470
Opened 2024-09-09 11:30 UTC by matejkarasek

This PR extends the functionality of the HL commander by 1) a linear GOTO command and 2) a spiral.
More details in the corresponding firmware PR:
segment.https://github.com/bitcraze/crazyflie-firmware/pull/1410

2024-09-23 09:27 UTC, ataffanel commented
It seems that this PR will make the lib incompatible with previous version of the firmware.

Since the lib is currently not checking for the protocol version and locking connection, it needs to stay compatible with the old message. Either by checking the version and sending the appropriate message (maybe with a warning to update the Crazyflie), or by adding the new message in a new function.

2024-09-25 13:25 UTC, matejkarasek commented
So I made a new function.
Checking for the may have been more elegant, however, I have not found a way how to do that...

2024-09-27 07:42 UTC, knmcguire commented
I've just approved the CI run as that hasn't been done yet, so please check if there are any errors there. 

Also for the review we'll need to try this out ourselves just to make sure that everything still works, so we will try to do that before the next release.

Yes absolutely, that would be a nice feature. I'm not sure if we have a issue/ticket for the version checking yet. 🤔

2024-09-30 09:24 UTC, knmcguire commented
The CI has failed on some autopep8 checks. @gemenerik will take a look at your PRs for test flight so if he can he'll fix it or you can fix it as well. 

You can also run the test locally on your computer with the toolbelt: https://www.bitcraze.io/documentation/repository/toolbelt/master/ and `tb verify`. It should work for windows as well but there are some ifs/buts for the instructions.

2024-10-01 06:02 UTC, matejkarasek commented
Thanks, the failed checks should now be fixed.

I have tested this on the crazyflie with both the latest release as well as with the new firmware https://github.com/bitcraze/crazyflie-firmware/pull/1410. All works as expected. 

But indeed this should be tested by someone else before it gets pulled into master.

2024-10-01 09:40 UTC, gemenerik requested changes

2024-10-01 09:40 UTC, gemenerik commented on cflib/crazyflie/high_level_commander.py
> +    def go_to2(self, x, y, z, yaw, duration_s, relative=False, linear=False,
I understand that this approach was suggested, but I believe a protocol version check could offer a simple and more elegant solution. Here's an example:

 ```python
import warning

...

    def go_to(self, x, y, z, yaw, duration_s, relative=False, linear=False,
              group_mask=ALL_GROUPS):
        """
        Go to an absolute or relative position

        :param x: X (m)
        :param y: Y (m)
        :param z: Z (m)
        :param yaw: Yaw (radians)
        :param duration_s: Time it should take to reach the position (s)
        :param relative: True if x, y, z is relative to the current position
        :param linear: True to use linear interpolation instead of a smooth polynomial
        :param group_mask: Mask for which CFs this should apply to
        """
        if self._cf.platform.get_protocol_version() < 8:
            if linear:
                warnings.warning("Linear mode is not supported in protocol version < 8, update your Crazyflie firmware")
            self._send_packet(struct.pack('<BBBfffff',
                                        self.COMMAND_GO_TO,
                                        group_mask,
                                        relative,
                                        x, y, z,
                                        yaw,
                                        duration_s))
        else:
            self._send_packet(struct.pack('<BBBBfffff',
                                self.COMMAND_GO_TO_2,
                                group_mask,
                                relative,
                                linear,
                                x, y, z,
                                yaw,
                                duration_s))
```

2024-10-01 13:43 UTC, matejkarasek commented on cflib/crazyflie/high_level_commander.py
> +    def go_to2(self, x, y, z, yaw, duration_s, relative=False, linear=False,
Thanks for checking @gemenerik 
I was looking for that function, somehow I missed that :)

I will modify it as you suggest 👍

2024-10-03 17:10 UTC, matejkarasek reviewed
All should be fixed as requested. Succesfully flight tested

2024-10-04 09:00 UTC, gemenerik approved these changes

2024-10-04 09:00 UTC, merged